blog-repo/blog/apps/post/urls.py
from django.urls import path
from apps.post import views as views

app_name='post'

#siempre revisar sintaxis si usamos todo plural o todo singular(users/profile > ruta del link)
urlpatterns = [
    path("posts/<slug:slug>", views.PostDetailView.as_view(), name='post_detail'),
    
]

blog-repo/blog/apps/user/urls.py
from django.urls import path
from apps.user import views as views

app_name='user'

#siempre revisar sintaxis si usamos todo plural o todo singular(users/profile > ruta del link)
urlpatterns = [
    path("users/profile", views.UserProfileView.as_view(), name='user_profile'),
    
]

blog-repo/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from blog.views import IndexView #importamos desde views la funcion index

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', IndexView.as_view(), name='home'), #path indica la ruta url, indicando el archivo html
    path("__reload__/", include("django_browser_reload.urls")),
    path('', include('apps.user.urls')),
    path('', include('apps.post.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog-repo/blog/apps/post/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.utils.text import slugify
import uuid
import os
    

class Category (models.Model):
    title = models.CharField(max_length=30)

    def __str__(self):
        return self.title
    

class Post(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='post')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    titulo=models.CharField(max_length=50)
    slug = models.SlugField(unique=True, max_length=200, blank=True)
    content =models.TextField(max_length=10000)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    allow_comments = models.BooleanField(default=True)
    #para likes, estrellas, favoritos, se asocia a post
    
    def __str__(self):
        return self.titulo
    
    @property
    def amount_comments(self):
        return self.comments.count()
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self.generate_unique_slug()
    
    def gernerate_unique_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        num = 1

        while Post.objects.filter(slug=unique_slug).exists(): 
            unique_slug = f'{slug}-{num}'
            num += 1
    
        return unique_slug


class Comment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name= 'comments')
    content =models.TextField(max_length=400)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)


def get_image_filename(instance, filename):
    post_id = instance.post.id
    images_count = instance.post.images.count()
    #miimagen.png
    #miimagen   .png
    _, file_extension = os.path.splitext(filename)
    new_filename = f'post_{post_id}_image_{images_count+1}{file_extension}'
    return os.path.join('post/cover/', new_filename)

class PostImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=get_image_filename)
    active = models.BooleanField(default=True)

    def __str__(self):
        return f'PostImage {self.id}'

blog-repo/blog/apps/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid
import os

def get_avatar_filename(instance, filename):
    # avatar_default.jpm
    # avatar_default   .jpg
    base_filename, file_extension = os.path.splitext(filename)
    new_filename = f'user_{instance.id}_acatar{file_extension}'
    return os.path.join('user/avatar/', new_filename)

class User(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    alias = models.CharField(max_length=50, blank=True)
    avatar = models.ImageField(upload_to=get_avatar_filename, default='user/default/avatar_default.jpg')

    def __str__(self):
        return self.username

    @property
    def is_registered(self):
        return self.groups.filter(name="Registered").exists()

    @property
    def is_collaborator(self):
        return self.groups.filter(name="Collaborators").exists()
    
    @property
    def is_admin(self):
        return self.groups.filter(name="Admins").exists()

blog-repo/blog/apps/post/views.py
from django.views.generic import TemplateView

class PostDetailView(TemplateView):
    template_name = 'post/post_detail.html'

blog-repo/blog/apps/user/views.py
from django.views.generic import TemplateView

class UserProfileView(TemplateView):
    template_name = 'user/user_profile.html'
    

blog-repo/blog/blog/views.py
from django.views.generic import TemplateView

class IndexView(TemplateView):
    template_name = 'index.html'
    

blog-repo/blog/templates/components/commons/footer.html
<footer class="relative bg-blueGray-200 pt-8 pb-6">
    <div class="container mx-auto px-4">
        <div class="flex flex-wrap text-left lg:text-left">
            <div class="w-full lg:w-6/12 px-4">
                <h4 class="text-3xl fonat-semibold text-blueGray-700">Let's keep in touch!</h4>
                <h5 class="text-lg mt-0 mb-2 text-blueGray-600">
                    Find us on any of these platforms, we respond 1-2 business days.
                </h5>
                <div class="mt-6 lg:mb-0 mb-6">
                    <button
                        class="bg-white text-lightBlue-400 shadow-lg font-normal h-10 w-10 items-center justify-center align-center rounded-full outline-none focus:outline-none mr-2"
                        type="button">
                        <i class="fab fa-twitter"></i></button><button
                        class="bg-white text-lightBlue-600 shadow-lg font-normal h-10 w-10 items-center justify-center align-center rounded-full outline-none focus:outline-none mr-2"
                        type="button">
                        <i class="fab fa-facebook-square"></i></button><button
                        class="bg-white text-pink-400 shadow-lg font-normal h-10 w-10 items-center justify-center align-center rounded-full outline-none focus:outline-none mr-2"
                        type="button">
                        <i class="fab fa-dribbble"></i></button><button
                        class="bg-white text-blueGray-800 shadow-lg font-normal h-10 w-10 items-center justify-center align-center rounded-full outline-none focus:outline-none mr-2"
                        type="button">
                        <i class="fab fa-github"></i>
                    </button>
                </div>
            </div>
            <div class="w-full lg:w-6/12 px-4">
                <div class="flex flex-wrap items-top mb-6">
                    <div class="w-full lg:w-4/12 px-4 ml-auto">
                        <span class="block uppercase text-blueGray-500 text-sm font-semibold mb-2">Useful Links</span>
                        <ul class="list-unstyled">
                            <li>
                                <a class="text-blueGray-600 hover:text-blueGray-800 font-semibold block pb-2 text-sm"
                                    href="https://www.creative-tim.com/presentation?ref=njs-profile">About Us</a>
                            </li>
                            <li>
                                <a class="text-blueGray-600 hover:text-blueGray-800 font-semibold block pb-2 text-sm"
                                    href="https://blog.creative-tim.com?ref=njs-profile">Blog</a>
                            </li>
                            <li>
                                <a class="text-blueGray-600 hover:text-blueGray-800 font-semibold block pb-2 text-sm"
                                    href="https://www.github.com/creativetimofficial?ref=njs-profile">Github</a>
                            </li>
                            <li>
                                <a class="text-blueGray-600 hover:text-blueGray-800 font-semibold block pb-2 text-sm"
                                    href="https://www.creative-tim.com/bootstrap-themes/free?ref=njs-profile">Free
                                    Products</a>
                            </li>
                        </ul>
                    </div>
                    <div class="w-full lg:w-4/12 px-4">
                        <span class="block uppercase text-blueGray-500 text-sm font-semibold mb-2">Other
                            Resources</span>
                        <ul class="list-unstyled">
                            <li>
                                <a class="text-blueGray-600 hover:text-blueGray-800 font-semibold block pb-2 text-sm"
                                    href="https://github.com/creativetimofficial/notus-js/blob/main/LICENSE.md?ref=njs-profile">MIT
                                    License</a>
                            </li>
                            <li>
                                <a class="text-blueGray-600 hover:text-blueGray-800 font-semibold block pb-2 text-sm"
                                    href="https://creative-tim.com/terms?ref=njs-profile">Terms &amp; Conditions</a>
                            </li>
                            <li>
                                <a class="text-blueGray-600 hover:text-blueGray-800 font-semibold block pb-2 text-sm"
                                    href="https://creative-tim.com/privacy?ref=njs-profile">Privacy Policy</a>
                            </li>
                            <li>
                                <a class="text-blueGray-600 hover:text-blueGray-800 font-semibold block pb-2 text-sm"
                                    href="https://creative-tim.com/contact-us?ref=njs-profile">Contact Us</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <hr class="my-6 border-blueGray-300">
        <div class="flex flex-wrap items-center md:justify-between justify-center">
            <div class="w-full md:w-4/12 px-4 mx-auto text-center">
                <div class="text-sm text-blueGray-500 font-semibold py-1">
                    Copyright © <span id="get-current-year">2021</span><a
                        href="https://www.creative-tim.com/product/notus-js"
                        class="text-blueGray-500 hover:text-gray-800" target="_blank"> Notus JS by
                        <a href="https://www.creative-tim.com?ref=njs-profile"
                            class="text-blueGray-500 hover:text-blueGray-800">Creative Tim</a>.
                </div>
            </div>
        </div>
    </div>
</footer>

blog-repo/blog/templates/components/commons/header.html
<header class="h-14 flex justify-center items-center text-white bg-orange-500 gap-4">
  <div class="container flex justify-between mx-4 md:mx-8 lg:mx-40">
    BLOG {% include 'components/ui/navbar.html' %}
  </div>
</header>

blog-repo/blog/templates/components/ui/navbar.html
<nav>
  <ul class="flex gap-4 ">
    <li><a href="{% url 'home' %}">Inicio</a></li>
    <li><a href="{% url 'user:user_profile' %}">Perfil</a></li>
  </ul>
</nav>

blog-repo/blog/templates/index.html
{% extends 'layouts/general_layout.html' %}

{% block title %} Inicio {% endblock title %}


{% block content %}
<main class="min-h-screen h-auto flex justify-center items-center bg-color-primary border-black border-[1px] flex-col">
  <div class="w-full lg:w-[74.5rem] items-center flex justify-center flex-col gap-5 my-8">
    <h1 class="text-5xl md:text-8xl font-semibold">Our News</h1>
    <p>Get the latest updates and deeper coffee experience from IMAJI Coffee</p>
    <div class="w-full md:w-[700px]">
      <img src="../static/fotoPortada.png" alt="Foto de portada">
    </div>
    <div class="w-full flex flex-col gap-2">
      <p class="text-3xl font-semibold">Collaboration to Develop Coffee and Beverage Industry Expertise in Indonesia</p>
      <span class="mb-8">4 Min 路 August 19, 2022</span>
    </div>
  </div>
</main>

<section class="flex justify-center items-center ">
  <div class="w-full lg:w-[74.5rem] items-center flex justify-center flex-col gap-5 my-6">
    <article class="w-full flex border-t-[1px] border-gray-400 gap-4 items-center p-4 flex-col lg:flex-row">
      <img src="../static/fotoBlog1.png" alt="">
      <div class="flex flex-col gap-3">
        <p class="text-4xl font-semibold">Visited Doesoen Sirap Coffee, The Producer of Robusta in Central Java</p>
        <span>4 Min 路 August 19, 2022</span>
      </div>
    </article>
    <article class="w-full flex border-t-[1px] border-gray-400 gap-4 items-center p-4 flex-col lg:flex-row">
      <img src="../static/fotoBlog1.png" alt="">
      <div class="flex flex-col gap-3">
        <p class="text-4xl font-semibold">Visited Doesoen Sirap Coffee, The Producer of Robusta in Central Java</p>
        <span>4 Min 路 August 19, 2022</span>
      </div>
    </article>
    <article class="w-full flex border-t-[1px] border-gray-400 gap-4 items-center p-4 flex-col lg:flex-row">
      <img src="../static/fotoBlog1.png" alt="">
      <div class="flex flex-col gap-3">
        <p class="text-4xl font-semibold">Visited Doesoen Sirap Coffee, The Producer of Robusta in Central Java</p>
        <span>4 Min 路 August 19, 2022</span>
      </div>
    </article>
    <article class="overflow-hidden rounded-lg shadow-sm transition hover:shadow-lg">
    </article>

  </div>
</section>
{% endblock content %}

blog-repo/blog/templates/layouts/auth_layout.html
{% extends 'layouts/base_layout.html' %}

blog-repo/blog/templates/layouts/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{% block title_layout %} {% endblock title_layout %}</title>
  <link rel="icon" href="{% static 'assets/favicon.ico' %}" type="image/x-icon" />
  {% block extra_head_layout %} {% endblock extra_head_layout %}
  <script type="module" src="{% static 'js/tailwind.js' %}"></script>
  <style type="text/tailwindcss">
    @theme {
        --breakpoint-xs: 30rem;
        --color-primary: #FCF7EF;
        --color-secondary: rgba(16, 24, 90);
      }
    </style>
</head>

<body class="min-w-[280px] bg-primary">
  {% block content_layout %} {% endblock content_layout %}
</body>
{% load django_browser_reload %}
{% django_browser_reload_script %}

</html>

blog-repo/blog/templates/layouts/general_layout.html
{% extends 'layouts/base_layout.html' %}

{% block title_layout %}
{% block title %}
IA
{% endblock title %}
| Blog
{% endblock title_layout %}

{% block extra_head_layout %}
{% block extra_head %} {% endblock extra_head %}
{% endblock extra_head_layout %}

{% block content_layout %}
{% include 'components/commons/header.html' %}
<main class="min-h-[calc(100dvh_-_112px)] flex justify-center flex-col">
  {% block content %} ⚠️ Colocar contenido {% endblock content %}
</main>
{% include 'components/commons/footer.html' %}
{% endblock content_layout %}

blog-repo/blog/templates/post/post_create.html
{% extends 'layout/general_layout.html' %}

blog-repo/blog/templates/post/post_delete.html
{% extends 'layout/general_layout.html' %}

blog-repo/blog/templates/post/post_detail.html
{% extends 'layouts/general_layout.html' %}

{% block title %} Post {% endblock title %}


{% block content %}
  Contenido del post
{% endblock content %}
  

blog-repo/blog/templates/user/user_profile.html
{% extends 'layouts/general_layout.html' %}

{% block title %} Perfil {% endblock title %}

{% block content %} 
  Perfil de usuario
{% endblock content %}